### ISSUE TITLE
Feature Request: Unique tokenization for method definitions and method calls

### ISSUE THREAD

**Issue by majidmadadi** [dannymcgee/vscode-csharp-grammar-extended#1]
Function call is different from function definition but the extension mark both of them as function definition.
The desired behavior is that function call is differentiated from declaration and thus colored by a color other than the color assigned to function definition.

**Comment by dannymcgee** [comment]
Hey @majidmadadi, thanks for the report! This grammar is derived from the one that comes with VS Code, but with a few added enhancements. The default grammar is pretty weak (hence why I made this extension), so it doesn't surprise me that it doesn't have this feature. It shouldn't be overly difficult to implement though. I'll look into it when I get the chance.

**Comment by dannymcgee** [comment]
(This is a note for future reference)

These are the TM scopes that the TypeScript grammar uses for this:
- `meta.definition.method.ts` (for the method name)
- `meta.method.declaration.ts` (for the entire block)
- `meta.function-call.ts` (for the entire expression)
- `entity.name.function.ts` (for all function or method names, regardless of context)

**Comment by dannymcgee** [comment]
This actually turned out to be really trivial to do, so it's done. :) Please let me know if you run into any situations where this is still incorrect.

Also, be aware that you will also need to use a theme that assigns different colors for method definitions and function invocations. This extension defines the grammar, but it doesn't determine which colors are assigned to which scopes.

Closed with d38ebd43ce6398e8ae30b4635cf15a2238465581 and 8af824d1388317953917d3a40ff5f6b1729bcffc

**Comment by majidmadadi** [comment]
It's solved. Awesome work👍
